### ISSUE TITLE
Unable to checkout cart

### ISSUE THREAD

**Issue by ciphertech** [drhenner/stripe_commerce#5]
I added a product in cart. When I try to checkout the cart sometimes it produces following error. Sometimes it even redirects to login page.
Here is the error:
ActiveRecord::RecordNotFound in Shopping::CartItemsController#update

Following is full error trace that I am getting:
activerecord (4.0.4) lib/active_record/nested_attributes.rb:543:in `raise_nested_attributes_record_not_found!'
activerecord (4.0.4) lib/active_record/nested_attributes.rb:480:in`block in assign_nested_attributes_for_collection_association'
activerecord (4.0.4) lib/active_record/nested_attributes.rb:456:in `each'
activerecord (4.0.4) lib/active_record/nested_attributes.rb:456:in`assign_nested_attributes_for_collection_association'
activerecord (4.0.4) lib/active_record/nested_attributes.rb:339:in `shopping_cart_items_attributes='
activerecord (4.0.4) lib/active_record/attribute_assignment.rb:42:in`public_send'
activerecord (4.0.4) lib/active_record/attribute_assignment.rb:42:in `_assign_attribute'
activerecord (4.0.4) lib/active_record/attribute_assignment.rb:53:in`block in assign_nested_parameter_attributes'
activerecord (4.0.4) lib/active_record/attribute_assignment.rb:53:in `each'
activerecord (4.0.4) lib/active_record/attribute_assignment.rb:53:in`assign_nested_parameter_attributes'
activerecord (4.0.4) lib/active_record/attribute_assignment.rb:33:in `assign_attributes'
activerecord (4.0.4) lib/active_record/persistence.rb:230:in`block in update'
activerecord (4.0.4) lib/active_record/transactions.rb:330:in `block in with_transaction_returning_status'
activerecord (4.0.4) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in`block in transaction'
activerecord (4.0.4) lib/active_record/connection_adapters/abstract/database_statements.rb:221:in `within_new_transaction'
activerecord (4.0.4) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in`transaction'
activerecord (4.0.4) lib/active_record/transactions.rb:209:in `transaction'
activerecord (4.0.4) lib/active_record/transactions.rb:327:in`with_transaction_returning_status'
activerecord (4.0.4) lib/active_record/persistence.rb:229:in `update'
app/controllers/shopping/cart_items_controller.rb:31:in`update'
actionpack (4.0.4) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.0.4) lib/abstract_controller/base.rb:189:in`process_action'
actionpack (4.0.4) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.0.4) lib/abstract_controller/callbacks.rb:18:in`block in process_action'
activesupport (4.0.4) lib/active_support/callbacks.rb:443:in `_run__1338144529671315106__process_action__callbacks'
activesupport (4.0.4) lib/active_support/callbacks.rb:80:in`run_callbacks'
actionpack (4.0.4) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (4.0.4) lib/action_controller/metal/rescue.rb:29:in`process_action'
actionpack (4.0.4) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.0.4) lib/active_support/notifications.rb:159:in`block in instrument'
activesupport (4.0.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.0.4) lib/active_support/notifications.rb:159:in`instrument'
actionpack (4.0.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.0.4) lib/action_controller/metal/params_wrapper.rb:250:in`process_action'
activerecord (4.0.4) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.0.4) lib/abstract_controller/base.rb:136:in`process'
actionpack (4.0.4) lib/abstract_controller/rendering.rb:44:in `process'
actionpack (4.0.4) lib/action_controller/metal.rb:195:in`dispatch'
actionpack (4.0.4) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.0.4) lib/action_controller/metal.rb:231:in`block in action'
actionpack (4.0.4) lib/action_dispatch/routing/route_set.rb:80:in `call'
actionpack (4.0.4) lib/action_dispatch/routing/route_set.rb:80:in`dispatch'
actionpack (4.0.4) lib/action_dispatch/routing/route_set.rb:48:in `call'
actionpack (4.0.4) lib/action_dispatch/journey/router.rb:71:in`block in call'
actionpack (4.0.4) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.0.4) lib/action_dispatch/journey/router.rb:59:in`call'
actionpack (4.0.4) lib/action_dispatch/routing/route_set.rb:674:in `call'
rack (1.5.2) lib/rack/etag.rb:23:in`call'
rack (1.5.2) lib/rack/conditionalget.rb:35:in `call'
rack (1.5.2) lib/rack/head.rb:11:in`call'
actionpack (4.0.4) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.0.4) lib/action_dispatch/middleware/flash.rb:241:in`call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in`call'
actionpack (4.0.4) lib/action_dispatch/middleware/cookies.rb:486:in `call'
activerecord (4.0.4) lib/active_record/query_cache.rb:36:in`call'
activerecord (4.0.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
actionpack (4.0.4) lib/action_dispatch/middleware/callbacks.rb:29:in`block in call'
activesupport (4.0.4) lib/active_support/callbacks.rb:373:in `_run__344584492997736513__call__callbacks'
activesupport (4.0.4) lib/active_support/callbacks.rb:80:in`run_callbacks'
actionpack (4.0.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.0.4) lib/action_dispatch/middleware/reloader.rb:64:in`call'
actionpack (4.0.4) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
better_errors (1.1.0) lib/better_errors/middleware.rb:58:in`call'
actionpack (4.0.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.0.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in`call'
railties (4.0.4) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.0.4) lib/rails/rack/logger.rb:20:in`block in call'
activesupport (4.0.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.0.4) lib/active_support/tagged_logging.rb:26:in`tagged'
activesupport (4.0.4) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.0.4) lib/rails/rack/logger.rb:20:in`call'
actionpack (4.0.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in`call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in`call'
rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
railties (4.0.4) lib/rails/engine.rb:511:in`call'
railties (4.0.4) lib/rails/application.rb:97:in `call'
railties (4.0.4) lib/rails/railtie/configurable.rb:30:in`method_missing'
rack (1.5.2) lib/rack/urlmap.rb:65:in `block in call'
rack (1.5.2) lib/rack/urlmap.rb:50:in`each'
rack (1.5.2) lib/rack/urlmap.rb:50:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in`process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in`main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'

**Comment by drhenner** [comment]
what are the params you pass in?

**Comment by ciphertech** [comment]
I have not passed any params. Not modified any code. I was just checking the checkout functionality.

**Comment by drhenner** [comment]
I'll try to load it up tonight after work

**Comment by drhenner** [comment]
So I am looking at this now...  It would be nice to know the `params` being passed in.  even if you don't modify the code.  The original code should have params.

**Comment by drhenner** [comment]
I need more details.  This work on my machine.

**Comment by drhenner** [comment]
Can you give me your db?

**Comment by drhenner** [comment]
This might happen if memcached is not setup properly.  Memcached is used for the session store
